/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */
#include "config.h"
#include "telnet_idl.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static tn_sense_1_ret_ *
_tn_sense_1_rpc_1 (tn_sense_1_rpc_1_argument *argp, struct svc_req *rqstp)
{
	return (tn_sense_1_rpc_1_svc(argp->arg1, argp->arg2, argp->arg3, argp->arg4, argp->arg5, argp->arg6, argp->arg7, argp->arg8, argp->arg9, rqstp));
}

static TerminalRead_ret_ *
_terminalread_rpc_1 (terminalread_rpc_1_argument *argp, struct svc_req *rqstp)
{
	return (terminalread_rpc_1_svc(argp->arg1, argp->arg2, rqstp));
}

static void *
_set_escape_1 (int  *argp, struct svc_req *rqstp)
{
	return (set_escape_1_svc(*argp, rqstp));
}

static void *
_tninit_rpc_1 (void  *argp, struct svc_req *rqstp)
{
	return (tninit_rpc_1_svc(rqstp));
}

static slc_mode_ret_t *
_get_slc_mode_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_slc_mode_1_svc(rqstp));
}

static void *
_set_slc_mode_1 (int  *argp, struct svc_req *rqstp)
{
	return (set_slc_mode_1_svc(*argp, rqstp));
}

static autologin_ret_t *
_get_autologin_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_autologin_1_svc(rqstp));
}

static void *
_set_autologin_1 (int  *argp, struct svc_req *rqstp)
{
	return (set_autologin_1_svc(*argp, rqstp));
}

static localflow_ret_t *
_get_localflow_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_localflow_1_svc(rqstp));
}

static void *
_set_localflow_1 (int  *argp, struct svc_req *rqstp)
{
	return (set_localflow_1_svc(*argp, rqstp));
}

static obits_ret_t *
_get_obits_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_obits_1_svc(rqstp));
}

static void *
_set_obits_1 (fd_set_rpc  *argp, struct svc_req *rqstp)
{
	return (set_obits_1_svc(*argp, rqstp));
}

static slc_reply_array *
_get_slc_reply_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_slc_reply_1_svc(rqstp));
}

static void *
_set_slc_reply_1 (slc_reply_array  *argp, struct svc_req *rqstp)
{
	return (set_slc_reply_1_svc(*argp, rqstp));
}

static netobuf_array *
_get_netobuf_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_netobuf_1_svc(rqstp));
}

static void *
_set_netobuf_1 (netobuf_array  *argp, struct svc_req *rqstp)
{
	return (set_netobuf_1_svc(*argp, rqstp));
}

static want_status_response_ret_t *
_get_want_status_response_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_want_status_response_1_svc(rqstp));
}

static void *
_set_want_status_response_1 (int  *argp, struct svc_req *rqstp)
{
	return (set_want_status_response_1_svc(*argp, rqstp));
}

static localchars_ret_t *
_get_localchars_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_localchars_1_svc(rqstp));
}

static void *
_set_localchars_1 (int  *argp, struct svc_req *rqstp)
{
	return (set_localchars_1_svc(*argp, rqstp));
}

static restartany_ret_t *
_get_restartany_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_restartany_1_svc(rqstp));
}

static void *
_set_restartany_1 (int  *argp, struct svc_req *rqstp)
{
	return (set_restartany_1_svc(*argp, rqstp));
}

static SYNCHing_ret_t *
_get_synching_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_synching_1_svc(rqstp));
}

static void *
_set_synching_1 (int  *argp, struct svc_req *rqstp)
{
	return (set_synching_1_svc(*argp, rqstp));
}

static termbuf_array *
_get_termbuf_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_termbuf_1_svc(rqstp));
}

static void *
_set_termbuf_1 (termbuf_array  *argp, struct svc_req *rqstp)
{
	return (set_termbuf_1_svc(*argp, rqstp));
}

static will_wont_resp_array *
_get_will_wont_resp_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_will_wont_resp_1_svc(rqstp));
}

static void *
_set_will_wont_resp_1 (will_wont_resp_array  *argp, struct svc_req *rqstp)
{
	return (set_will_wont_resp_1_svc(*argp, rqstp));
}

static autoflush_ret_t *
_get_autoflush_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_autoflush_1_svc(rqstp));
}

static void *
_set_autoflush_1 (int  *argp, struct svc_req *rqstp)
{
	return (set_autoflush_1_svc(*argp, rqstp));
}

static tin_ret_t *
_get_tin_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_tin_1_svc(rqstp));
}

static void *
_set_tin_1 (int  *argp, struct svc_req *rqstp)
{
	return (set_tin_1_svc(*argp, rqstp));
}

static xbits_ret_t *
_get_xbits_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_xbits_1_svc(rqstp));
}

static void *
_set_xbits_1 (fd_set_rpc  *argp, struct svc_req *rqstp)
{
	return (set_xbits_1_svc(*argp, rqstp));
}

static telrcv_state_ret_t *
_get_telrcv_state_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_telrcv_state_1_svc(rqstp));
}

static void *
_set_telrcv_state_1 (int  *argp, struct svc_req *rqstp)
{
	return (set_telrcv_state_1_svc(*argp, rqstp));
}

static ibits_ret_t *
_get_ibits_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_ibits_1_svc(rqstp));
}

static void *
_set_ibits_1 (fd_set_rpc  *argp, struct svc_req *rqstp)
{
	return (set_ibits_1_svc(*argp, rqstp));
}

static linemode_ret_t *
_get_linemode_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_linemode_1_svc(rqstp));
}

static void *
_set_linemode_1 (int  *argp, struct svc_req *rqstp)
{
	return (set_linemode_1_svc(*argp, rqstp));
}

static bol_ret_t *
_get_bol_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_bol_1_svc(rqstp));
}

static void *
_set_bol_1 (int  *argp, struct svc_req *rqstp)
{
	return (set_bol_1_svc(*argp, rqstp));
}

static options_array *
_get_options_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_options_1_svc(rqstp));
}

static void *
_set_options_1 (options_array  *argp, struct svc_req *rqstp)
{
	return (set_options_1_svc(*argp, rqstp));
}

static telopts_array *
_get_telopts_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_telopts_1_svc(rqstp));
}

static void *
_set_telopts_1 (telopts_array  *argp, struct svc_req *rqstp)
{
	return (set_telopts_1_svc(*argp, rqstp));
}

static str_lm_array *
_get_str_lm_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_str_lm_1_svc(rqstp));
}

static void *
_set_str_lm_1 (str_lm_array  *argp, struct svc_req *rqstp)
{
	return (set_str_lm_1_svc(*argp, rqstp));
}

static slc_import_val_array *
_get_slc_import_val_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_slc_import_val_1_svc(rqstp));
}

static void *
_set_slc_import_val_1 (slc_import_val_array  *argp, struct svc_req *rqstp)
{
	return (set_slc_import_val_1_svc(*argp, rqstp));
}

static clocks_ret_t *
_get_clocks_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_clocks_1_svc(rqstp));
}

static void *
_set_clocks_1 (Clocks_rpc  *argp, struct svc_req *rqstp)
{
	return (set_clocks_1_svc(*argp, rqstp));
}

static clocks_system_ret_t *
_get_clocks_system_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_clocks_system_1_svc(rqstp));
}

static void *
_set_clocks_system_1 (int  *argp, struct svc_req *rqstp)
{
	return (set_clocks_system_1_svc(*argp, rqstp));
}

static clocks_echotoggle_ret_t *
_get_clocks_echotoggle_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_clocks_echotoggle_1_svc(rqstp));
}

static void *
_set_clocks_echotoggle_1 (int  *argp, struct svc_req *rqstp)
{
	return (set_clocks_echotoggle_1_svc(*argp, rqstp));
}

static clocks_modenegotiated_ret_t *
_get_clocks_modenegotiated_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_clocks_modenegotiated_1_svc(rqstp));
}

static void *
_set_clocks_modenegotiated_1 (int  *argp, struct svc_req *rqstp)
{
	return (set_clocks_modenegotiated_1_svc(*argp, rqstp));
}

static clocks_didnetreceive_ret_t *
_get_clocks_didnetreceive_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_clocks_didnetreceive_1_svc(rqstp));
}

static void *
_set_clocks_didnetreceive_1 (int  *argp, struct svc_req *rqstp)
{
	return (set_clocks_didnetreceive_1_svc(*argp, rqstp));
}

static clocks_gotDM_ret_t *
_get_clocks_gotdm_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_clocks_gotdm_1_svc(rqstp));
}

static void *
_set_clocks_gotdm_1 (int  *argp, struct svc_req *rqstp)
{
	return (set_clocks_gotdm_1_svc(*argp, rqstp));
}

static netoring_ret_t *
_get_netoring_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_netoring_1_svc(rqstp));
}

static void *
_set_netoring_1 (Ring_rpc  *argp, struct svc_req *rqstp)
{
	return (set_netoring_1_svc(*argp, rqstp));
}

static netoring_consume_ret_t *
_get_netoring_consume_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_netoring_consume_1_svc(rqstp));
}

static void *
_set_netoring_consume_1 (char_ptr  *argp, struct svc_req *rqstp)
{
	return (set_netoring_consume_1_svc(*argp, rqstp));
}

static netoring_supply_ret_t *
_get_netoring_supply_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_netoring_supply_1_svc(rqstp));
}

static void *
_set_netoring_supply_1 (char_ptr  *argp, struct svc_req *rqstp)
{
	return (set_netoring_supply_1_svc(*argp, rqstp));
}

static netoring_bottom_ret_t *
_get_netoring_bottom_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_netoring_bottom_1_svc(rqstp));
}

static void *
_set_netoring_bottom_1 (char_ptr  *argp, struct svc_req *rqstp)
{
	return (set_netoring_bottom_1_svc(*argp, rqstp));
}

static netoring_top_ret_t *
_get_netoring_top_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_netoring_top_1_svc(rqstp));
}

static void *
_set_netoring_top_1 (char_ptr  *argp, struct svc_req *rqstp)
{
	return (set_netoring_top_1_svc(*argp, rqstp));
}

static netoring_mark_ret_t *
_get_netoring_mark_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_netoring_mark_1_svc(rqstp));
}

static void *
_set_netoring_mark_1 (char_ptr  *argp, struct svc_req *rqstp)
{
	return (set_netoring_mark_1_svc(*argp, rqstp));
}

static netoring_size_ret_t *
_get_netoring_size_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_netoring_size_1_svc(rqstp));
}

static void *
_set_netoring_size_1 (int  *argp, struct svc_req *rqstp)
{
	return (set_netoring_size_1_svc(*argp, rqstp));
}

static netoring_consumetime_ret_t *
_get_netoring_consumetime_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_netoring_consumetime_1_svc(rqstp));
}

static void *
_set_netoring_consumetime_1 (u_long  *argp, struct svc_req *rqstp)
{
	return (set_netoring_consumetime_1_svc(*argp, rqstp));
}

static netoring_supplytime_ret_t *
_get_netoring_supplytime_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_netoring_supplytime_1_svc(rqstp));
}

static void *
_set_netoring_supplytime_1 (u_long  *argp, struct svc_req *rqstp)
{
	return (set_netoring_supplytime_1_svc(*argp, rqstp));
}

static crmod_ret_t *
_get_crmod_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_crmod_1_svc(rqstp));
}

static void *
_set_crmod_1 (int  *argp, struct svc_req *rqstp)
{
	return (set_crmod_1_svc(*argp, rqstp));
}

static donebinarytoggle_ret_t *
_get_donebinarytoggle_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_donebinarytoggle_1_svc(rqstp));
}

static void *
_set_donebinarytoggle_1 (int  *argp, struct svc_req *rqstp)
{
	return (set_donebinarytoggle_1_svc(*argp, rqstp));
}

static ttyibuf_array *
_get_ttyibuf_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_ttyibuf_1_svc(rqstp));
}

static void *
_set_ttyibuf_1 (ttyibuf_array  *argp, struct svc_req *rqstp)
{
	return (set_ttyibuf_1_svc(*argp, rqstp));
}

static slc_import_def_array *
_get_slc_import_def_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_slc_import_def_1_svc(rqstp));
}

static void *
_set_slc_import_def_1 (slc_import_def_array  *argp, struct svc_req *rqstp)
{
	return (set_slc_import_def_1_svc(*argp, rqstp));
}

static resettermname_ret_t *
_get_resettermname_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_resettermname_1_svc(rqstp));
}

static void *
_set_resettermname_1 (int  *argp, struct svc_req *rqstp)
{
	return (set_resettermname_1_svc(*argp, rqstp));
}

static flushout_ret_t *
_get_flushout_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_flushout_1_svc(rqstp));
}

static void *
_set_flushout_1 (int  *argp, struct svc_req *rqstp)
{
	return (set_flushout_1_svc(*argp, rqstp));
}

static In3270_ret_t *
_get_in3270_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_in3270_1_svc(rqstp));
}

static void *
_set_in3270_1 (int  *argp, struct svc_req *rqstp)
{
	return (set_in3270_1_svc(*argp, rqstp));
}

static connected_ret_t *
_get_connected_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_connected_1_svc(rqstp));
}

static void *
_set_connected_1 (int  *argp, struct svc_req *rqstp)
{
	return (set_connected_1_svc(*argp, rqstp));
}

static new_tc_ret_t *
_get_new_tc_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_new_tc_1_svc(rqstp));
}

static void *
_set_new_tc_1 (termios_rpc  *argp, struct svc_req *rqstp)
{
	return (set_new_tc_1_svc(*argp, rqstp));
}

static new_tc_c_iflag_ret_t *
_get_new_tc_c_iflag_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_new_tc_c_iflag_1_svc(rqstp));
}

static void *
_set_new_tc_c_iflag_1 (u_int  *argp, struct svc_req *rqstp)
{
	return (set_new_tc_c_iflag_1_svc(*argp, rqstp));
}

static new_tc_c_oflag_ret_t *
_get_new_tc_c_oflag_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_new_tc_c_oflag_1_svc(rqstp));
}

static void *
_set_new_tc_c_oflag_1 (u_int  *argp, struct svc_req *rqstp)
{
	return (set_new_tc_c_oflag_1_svc(*argp, rqstp));
}

static new_tc_c_cflag_ret_t *
_get_new_tc_c_cflag_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_new_tc_c_cflag_1_svc(rqstp));
}

static void *
_set_new_tc_c_cflag_1 (u_int  *argp, struct svc_req *rqstp)
{
	return (set_new_tc_c_cflag_1_svc(*argp, rqstp));
}

static new_tc_c_lflag_ret_t *
_get_new_tc_c_lflag_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_new_tc_c_lflag_1_svc(rqstp));
}

static void *
_set_new_tc_c_lflag_1 (u_int  *argp, struct svc_req *rqstp)
{
	return (set_new_tc_c_lflag_1_svc(*argp, rqstp));
}

static new_tc_c_line_ret_t *
_get_new_tc_c_line_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_new_tc_c_line_1_svc(rqstp));
}

static void *
_set_new_tc_c_line_1 (u_char  *argp, struct svc_req *rqstp)
{
	return (set_new_tc_c_line_1_svc(*argp, rqstp));
}

static new_tc_c_ispeed_ret_t *
_get_new_tc_c_ispeed_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_new_tc_c_ispeed_1_svc(rqstp));
}

static void *
_set_new_tc_c_ispeed_1 (u_int  *argp, struct svc_req *rqstp)
{
	return (set_new_tc_c_ispeed_1_svc(*argp, rqstp));
}

static new_tc_c_ospeed_ret_t *
_get_new_tc_c_ospeed_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_new_tc_c_ospeed_1_svc(rqstp));
}

static void *
_set_new_tc_c_ospeed_1 (u_int  *argp, struct svc_req *rqstp)
{
	return (set_new_tc_c_ospeed_1_svc(*argp, rqstp));
}

static netiring_ret_t *
_get_netiring_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_netiring_1_svc(rqstp));
}

static void *
_set_netiring_1 (Ring_rpc  *argp, struct svc_req *rqstp)
{
	return (set_netiring_1_svc(*argp, rqstp));
}

static netiring_consume_ret_t *
_get_netiring_consume_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_netiring_consume_1_svc(rqstp));
}

static void *
_set_netiring_consume_1 (char_ptr  *argp, struct svc_req *rqstp)
{
	return (set_netiring_consume_1_svc(*argp, rqstp));
}

static netiring_supply_ret_t *
_get_netiring_supply_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_netiring_supply_1_svc(rqstp));
}

static void *
_set_netiring_supply_1 (char_ptr  *argp, struct svc_req *rqstp)
{
	return (set_netiring_supply_1_svc(*argp, rqstp));
}

static netiring_bottom_ret_t *
_get_netiring_bottom_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_netiring_bottom_1_svc(rqstp));
}

static void *
_set_netiring_bottom_1 (char_ptr  *argp, struct svc_req *rqstp)
{
	return (set_netiring_bottom_1_svc(*argp, rqstp));
}

static netiring_top_ret_t *
_get_netiring_top_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_netiring_top_1_svc(rqstp));
}

static void *
_set_netiring_top_1 (char_ptr  *argp, struct svc_req *rqstp)
{
	return (set_netiring_top_1_svc(*argp, rqstp));
}

static netiring_mark_ret_t *
_get_netiring_mark_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_netiring_mark_1_svc(rqstp));
}

static void *
_set_netiring_mark_1 (char_ptr  *argp, struct svc_req *rqstp)
{
	return (set_netiring_mark_1_svc(*argp, rqstp));
}

static netiring_size_ret_t *
_get_netiring_size_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_netiring_size_1_svc(rqstp));
}

static void *
_set_netiring_size_1 (int  *argp, struct svc_req *rqstp)
{
	return (set_netiring_size_1_svc(*argp, rqstp));
}

static netiring_consumetime_ret_t *
_get_netiring_consumetime_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_netiring_consumetime_1_svc(rqstp));
}

static void *
_set_netiring_consumetime_1 (u_long  *argp, struct svc_req *rqstp)
{
	return (set_netiring_consumetime_1_svc(*argp, rqstp));
}

static netiring_supplytime_ret_t *
_get_netiring_supplytime_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_netiring_supplytime_1_svc(rqstp));
}

static void *
_set_netiring_supplytime_1 (u_long  *argp, struct svc_req *rqstp)
{
	return (set_netiring_supplytime_1_svc(*argp, rqstp));
}

static tout_ret_t *
_get_tout_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_tout_1_svc(rqstp));
}

static void *
_set_tout_1 (int  *argp, struct svc_req *rqstp)
{
	return (set_tout_1_svc(*argp, rqstp));
}

static netibuf_array *
_get_netibuf_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_netibuf_1_svc(rqstp));
}

static void *
_set_netibuf_1 (netibuf_array  *argp, struct svc_req *rqstp)
{
	return (set_netibuf_1_svc(*argp, rqstp));
}

static eight_ret_t *
_get_eight_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_eight_1_svc(rqstp));
}

static void *
_set_eight_1 (int  *argp, struct svc_req *rqstp)
{
	return (set_eight_1_svc(*argp, rqstp));
}

static telnetport_ret_t *
_get_telnetport_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_telnetport_1_svc(rqstp));
}

static void *
_set_telnetport_1 (int  *argp, struct svc_req *rqstp)
{
	return (set_telnetport_1_svc(*argp, rqstp));
}

static do_dont_resp_array *
_get_do_dont_resp_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_do_dont_resp_1_svc(rqstp));
}

static void *
_set_do_dont_resp_1 (do_dont_resp_array  *argp, struct svc_req *rqstp)
{
	return (set_do_dont_resp_1_svc(*argp, rqstp));
}

static saveline_array *
_get_saveline_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_saveline_1_svc(rqstp));
}

static void *
_set_saveline_1 (saveline_array  *argp, struct svc_req *rqstp)
{
	return (set_saveline_1_svc(*argp, rqstp));
}

static old_tc_ret_t *
_get_old_tc_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_old_tc_1_svc(rqstp));
}

static void *
_set_old_tc_1 (termios_rpc  *argp, struct svc_req *rqstp)
{
	return (set_old_tc_1_svc(*argp, rqstp));
}

static old_tc_c_iflag_ret_t *
_get_old_tc_c_iflag_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_old_tc_c_iflag_1_svc(rqstp));
}

static void *
_set_old_tc_c_iflag_1 (u_int  *argp, struct svc_req *rqstp)
{
	return (set_old_tc_c_iflag_1_svc(*argp, rqstp));
}

static old_tc_c_oflag_ret_t *
_get_old_tc_c_oflag_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_old_tc_c_oflag_1_svc(rqstp));
}

static void *
_set_old_tc_c_oflag_1 (u_int  *argp, struct svc_req *rqstp)
{
	return (set_old_tc_c_oflag_1_svc(*argp, rqstp));
}

static old_tc_c_cflag_ret_t *
_get_old_tc_c_cflag_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_old_tc_c_cflag_1_svc(rqstp));
}

static void *
_set_old_tc_c_cflag_1 (u_int  *argp, struct svc_req *rqstp)
{
	return (set_old_tc_c_cflag_1_svc(*argp, rqstp));
}

static old_tc_c_lflag_ret_t *
_get_old_tc_c_lflag_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_old_tc_c_lflag_1_svc(rqstp));
}

static void *
_set_old_tc_c_lflag_1 (u_int  *argp, struct svc_req *rqstp)
{
	return (set_old_tc_c_lflag_1_svc(*argp, rqstp));
}

static old_tc_c_line_ret_t *
_get_old_tc_c_line_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_old_tc_c_line_1_svc(rqstp));
}

static void *
_set_old_tc_c_line_1 (u_char  *argp, struct svc_req *rqstp)
{
	return (set_old_tc_c_line_1_svc(*argp, rqstp));
}

static old_tc_c_ispeed_ret_t *
_get_old_tc_c_ispeed_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_old_tc_c_ispeed_1_svc(rqstp));
}

static void *
_set_old_tc_c_ispeed_1 (u_int  *argp, struct svc_req *rqstp)
{
	return (set_old_tc_c_ispeed_1_svc(*argp, rqstp));
}

static old_tc_c_ospeed_ret_t *
_get_old_tc_c_ospeed_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_old_tc_c_ospeed_1_svc(rqstp));
}

static void *
_set_old_tc_c_ospeed_1 (u_int  *argp, struct svc_req *rqstp)
{
	return (set_old_tc_c_ospeed_1_svc(*argp, rqstp));
}

static margv_array *
_get_margv_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_margv_1_svc(rqstp));
}

static void *
_set_margv_1 (margv_array  *argp, struct svc_req *rqstp)
{
	return (set_margv_1_svc(*argp, rqstp));
}

static line_array *
_get_line_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_line_1_svc(rqstp));
}

static void *
_set_line_1 (line_array  *argp, struct svc_req *rqstp)
{
	return (set_line_1_svc(*argp, rqstp));
}

static flushline_ret_t *
_get_flushline_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_flushline_1_svc(rqstp));
}

static void *
_set_flushline_1 (int  *argp, struct svc_req *rqstp)
{
	return (set_flushline_1_svc(*argp, rqstp));
}

static debug_ret_t *
_get_debug_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_debug_1_svc(rqstp));
}

static void *
_set_debug_1 (int  *argp, struct svc_req *rqstp)
{
	return (set_debug_1_svc(*argp, rqstp));
}

static ring_clock_ret_t *
_get_ring_clock_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_ring_clock_1_svc(rqstp));
}

static void *
_set_ring_clock_1 (u_long  *argp, struct svc_req *rqstp)
{
	return (set_ring_clock_1_svc(*argp, rqstp));
}

static str_lm_mode_array *
_get_str_lm_mode_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_str_lm_mode_1_svc(rqstp));
}

static void *
_set_str_lm_mode_1 (str_lm_mode_array  *argp, struct svc_req *rqstp)
{
	return (set_str_lm_mode_1_svc(*argp, rqstp));
}

static ISend_ret_t *
_get_isend_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_isend_1_svc(rqstp));
}

static void *
_set_isend_1 (int  *argp, struct svc_req *rqstp)
{
	return (set_isend_1_svc(*argp, rqstp));
}

static dontlecho_ret_t *
_get_dontlecho_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_dontlecho_1_svc(rqstp));
}

static void *
_set_dontlecho_1 (int  *argp, struct svc_req *rqstp)
{
	return (set_dontlecho_1_svc(*argp, rqstp));
}

static kludgelinemode_ret_t *
_get_kludgelinemode_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_kludgelinemode_1_svc(rqstp));
}

static void *
_set_kludgelinemode_1 (int  *argp, struct svc_req *rqstp)
{
	return (set_kludgelinemode_1_svc(*argp, rqstp));
}

static net_ret_t *
_get_net_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_net_1_svc(rqstp));
}

static void *
_set_net_1 (int  *argp, struct svc_req *rqstp)
{
	return (set_net_1_svc(*argp, rqstp));
}

static char_ptr *
_get_hostname_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_hostname_1_svc(rqstp));
}

static void *
_set_hostname_1 (char_ptr  *argp, struct svc_req *rqstp)
{
	return (set_hostname_1_svc(*argp, rqstp));
}

static margc_ret_t *
_get_margc_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_margc_1_svc(rqstp));
}

static void *
_set_margc_1 (int  *argp, struct svc_req *rqstp)
{
	return (set_margc_1_svc(*argp, rqstp));
}

static globalmode_ret_t *
_get_globalmode_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_globalmode_1_svc(rqstp));
}

static void *
_set_globalmode_1 (int  *argp, struct svc_req *rqstp)
{
	return (set_globalmode_1_svc(*argp, rqstp));
}

static skiprc_ret_t *
_get_skiprc_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_skiprc_1_svc(rqstp));
}

static void *
_set_skiprc_1 (int  *argp, struct svc_req *rqstp)
{
	return (set_skiprc_1_svc(*argp, rqstp));
}

static char_ptr *
_get_nettrace_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_nettrace_1_svc(rqstp));
}

static void *
_set_nettrace_1 (char_ptr  *argp, struct svc_req *rqstp)
{
	return (set_nettrace_1_svc(*argp, rqstp));
}

static ttyiring_ret_t *
_get_ttyiring_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_ttyiring_1_svc(rqstp));
}

static void *
_set_ttyiring_1 (Ring_rpc  *argp, struct svc_req *rqstp)
{
	return (set_ttyiring_1_svc(*argp, rqstp));
}

static ttyiring_consume_ret_t *
_get_ttyiring_consume_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_ttyiring_consume_1_svc(rqstp));
}

static void *
_set_ttyiring_consume_1 (char_ptr  *argp, struct svc_req *rqstp)
{
	return (set_ttyiring_consume_1_svc(*argp, rqstp));
}

static ttyiring_supply_ret_t *
_get_ttyiring_supply_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_ttyiring_supply_1_svc(rqstp));
}

static void *
_set_ttyiring_supply_1 (char_ptr  *argp, struct svc_req *rqstp)
{
	return (set_ttyiring_supply_1_svc(*argp, rqstp));
}

static ttyiring_bottom_ret_t *
_get_ttyiring_bottom_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_ttyiring_bottom_1_svc(rqstp));
}

static void *
_set_ttyiring_bottom_1 (char_ptr  *argp, struct svc_req *rqstp)
{
	return (set_ttyiring_bottom_1_svc(*argp, rqstp));
}

static ttyiring_top_ret_t *
_get_ttyiring_top_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_ttyiring_top_1_svc(rqstp));
}

static void *
_set_ttyiring_top_1 (char_ptr  *argp, struct svc_req *rqstp)
{
	return (set_ttyiring_top_1_svc(*argp, rqstp));
}

static ttyiring_mark_ret_t *
_get_ttyiring_mark_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_ttyiring_mark_1_svc(rqstp));
}

static void *
_set_ttyiring_mark_1 (char_ptr  *argp, struct svc_req *rqstp)
{
	return (set_ttyiring_mark_1_svc(*argp, rqstp));
}

static ttyiring_size_ret_t *
_get_ttyiring_size_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_ttyiring_size_1_svc(rqstp));
}

static void *
_set_ttyiring_size_1 (int  *argp, struct svc_req *rqstp)
{
	return (set_ttyiring_size_1_svc(*argp, rqstp));
}

static ttyiring_consumetime_ret_t *
_get_ttyiring_consumetime_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_ttyiring_consumetime_1_svc(rqstp));
}

static void *
_set_ttyiring_consumetime_1 (u_long  *argp, struct svc_req *rqstp)
{
	return (set_ttyiring_consumetime_1_svc(*argp, rqstp));
}

static ttyiring_supplytime_ret_t *
_get_ttyiring_supplytime_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_ttyiring_supplytime_1_svc(rqstp));
}

static void *
_set_ttyiring_supplytime_1 (u_long  *argp, struct svc_req *rqstp)
{
	return (set_ttyiring_supplytime_1_svc(*argp, rqstp));
}

static char_ptr *
_get_prompt_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_prompt_1_svc(rqstp));
}

static void *
_set_prompt_1 (char_ptr  *argp, struct svc_req *rqstp)
{
	return (set_prompt_1_svc(*argp, rqstp));
}

static char_ptr *
_get_user_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_user_1_svc(rqstp));
}

static void *
_set_user_1 (char_ptr  *argp, struct svc_req *rqstp)
{
	return (set_user_1_svc(*argp, rqstp));
}

static char_ptr *
_get_rcname_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_rcname_1_svc(rqstp));
}

static void *
_set_rcname_1 (char_ptr  *argp, struct svc_req *rqstp)
{
	return (set_rcname_1_svc(*argp, rqstp));
}

static local_ret_t *
_get_local_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_local_1_svc(rqstp));
}

static void *
_set_local_1 (int  *argp, struct svc_req *rqstp)
{
	return (set_local_1_svc(*argp, rqstp));
}

static ttyoring_ret_t *
_get_ttyoring_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_ttyoring_1_svc(rqstp));
}

static void *
_set_ttyoring_1 (Ring_rpc  *argp, struct svc_req *rqstp)
{
	return (set_ttyoring_1_svc(*argp, rqstp));
}

static ttyoring_consume_ret_t *
_get_ttyoring_consume_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_ttyoring_consume_1_svc(rqstp));
}

static void *
_set_ttyoring_consume_1 (char_ptr  *argp, struct svc_req *rqstp)
{
	return (set_ttyoring_consume_1_svc(*argp, rqstp));
}

static ttyoring_supply_ret_t *
_get_ttyoring_supply_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_ttyoring_supply_1_svc(rqstp));
}

static void *
_set_ttyoring_supply_1 (char_ptr  *argp, struct svc_req *rqstp)
{
	return (set_ttyoring_supply_1_svc(*argp, rqstp));
}

static ttyoring_bottom_ret_t *
_get_ttyoring_bottom_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_ttyoring_bottom_1_svc(rqstp));
}

static void *
_set_ttyoring_bottom_1 (char_ptr  *argp, struct svc_req *rqstp)
{
	return (set_ttyoring_bottom_1_svc(*argp, rqstp));
}

static ttyoring_top_ret_t *
_get_ttyoring_top_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_ttyoring_top_1_svc(rqstp));
}

static void *
_set_ttyoring_top_1 (char_ptr  *argp, struct svc_req *rqstp)
{
	return (set_ttyoring_top_1_svc(*argp, rqstp));
}

static ttyoring_mark_ret_t *
_get_ttyoring_mark_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_ttyoring_mark_1_svc(rqstp));
}

static void *
_set_ttyoring_mark_1 (char_ptr  *argp, struct svc_req *rqstp)
{
	return (set_ttyoring_mark_1_svc(*argp, rqstp));
}

static ttyoring_size_ret_t *
_get_ttyoring_size_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_ttyoring_size_1_svc(rqstp));
}

static void *
_set_ttyoring_size_1 (int  *argp, struct svc_req *rqstp)
{
	return (set_ttyoring_size_1_svc(*argp, rqstp));
}

static ttyoring_consumetime_ret_t *
_get_ttyoring_consumetime_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_ttyoring_consumetime_1_svc(rqstp));
}

static void *
_set_ttyoring_consumetime_1 (u_long  *argp, struct svc_req *rqstp)
{
	return (set_ttyoring_consumetime_1_svc(*argp, rqstp));
}

static ttyoring_supplytime_ret_t *
_get_ttyoring_supplytime_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_ttyoring_supplytime_1_svc(rqstp));
}

static void *
_set_ttyoring_supplytime_1 (u_long  *argp, struct svc_req *rqstp)
{
	return (set_ttyoring_supplytime_1_svc(*argp, rqstp));
}

static ttyobuf_array *
_get_ttyobuf_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_ttyobuf_1_svc(rqstp));
}

static void *
_set_ttyobuf_1 (ttyobuf_array  *argp, struct svc_req *rqstp)
{
	return (set_ttyobuf_1_svc(*argp, rqstp));
}

static subbuffer_array *
_get_subbuffer_1 (void  *argp, struct svc_req *rqstp)
{
	return (get_subbuffer_1_svc(rqstp));
}

static void *
_set_subbuffer_1 (subbuffer_array  *argp, struct svc_req *rqstp)
{
	return (set_subbuffer_1_svc(*argp, rqstp));
}

static int *
_gsetter_want_status_response_prefix_1 (void  *argp, struct svc_req *rqstp)
{
	return (gsetter_want_status_response_prefix_1_svc(rqstp));
}

static int *
_gsetter_margc_postfix_1 (void  *argp, struct svc_req *rqstp)
{
	return (gsetter_margc_postfix_1_svc(rqstp));
}

static void *
_gsetter_prompt_prefix_1 (void  *argp, struct svc_req *rqstp)
{
	return (gsetter_prompt_prefix_1_svc(rqstp));
}

static char_ptr *
_gsetter_subpointer_postfix_1 (void  *argp, struct svc_req *rqstp)
{
	return (gsetter_subpointer_postfix_1_svc(rqstp));
}

static char_ptr *
_gsetter_slc_replyp_postfix_1 (void  *argp, struct svc_req *rqstp)
{
	return (gsetter_slc_replyp_postfix_1_svc(rqstp));
}

static char_ptr *
_gsetter_opt_replyp_postfix_1 (void  *argp, struct svc_req *rqstp)
{
	return (gsetter_opt_replyp_postfix_1_svc(rqstp));
}

static u_long *
_gsetter_ring_clock_prefix_1 (void  *argp, struct svc_req *rqstp)
{
	return (gsetter_ring_clock_prefix_1_svc(rqstp));
}

static void
rpctelnet_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		tn_sense_1_rpc_1_argument tn_sense_1_rpc_1_arg;
		terminalread_rpc_1_argument terminalread_rpc_1_arg;
		int set_escape_1_arg;
		int set_slc_mode_1_arg;
		int set_autologin_1_arg;
		int set_localflow_1_arg;
		fd_set_rpc set_obits_1_arg;
		slc_reply_array set_slc_reply_1_arg;
		netobuf_array set_netobuf_1_arg;
		int set_want_status_response_1_arg;
		int set_localchars_1_arg;
		int set_restartany_1_arg;
		int set_synching_1_arg;
		termbuf_array set_termbuf_1_arg;
		will_wont_resp_array set_will_wont_resp_1_arg;
		int set_autoflush_1_arg;
		int set_tin_1_arg;
		fd_set_rpc set_xbits_1_arg;
		int set_telrcv_state_1_arg;
		fd_set_rpc set_ibits_1_arg;
		int set_linemode_1_arg;
		int set_bol_1_arg;
		options_array set_options_1_arg;
		telopts_array set_telopts_1_arg;
		str_lm_array set_str_lm_1_arg;
		slc_import_val_array set_slc_import_val_1_arg;
		Clocks_rpc set_clocks_1_arg;
		int set_clocks_system_1_arg;
		int set_clocks_echotoggle_1_arg;
		int set_clocks_modenegotiated_1_arg;
		int set_clocks_didnetreceive_1_arg;
		int set_clocks_gotdm_1_arg;
		Ring_rpc set_netoring_1_arg;
		char_ptr set_netoring_consume_1_arg;
		char_ptr set_netoring_supply_1_arg;
		char_ptr set_netoring_bottom_1_arg;
		char_ptr set_netoring_top_1_arg;
		char_ptr set_netoring_mark_1_arg;
		int set_netoring_size_1_arg;
		u_long set_netoring_consumetime_1_arg;
		u_long set_netoring_supplytime_1_arg;
		int set_crmod_1_arg;
		int set_donebinarytoggle_1_arg;
		ttyibuf_array set_ttyibuf_1_arg;
		slc_import_def_array set_slc_import_def_1_arg;
		int set_resettermname_1_arg;
		int set_flushout_1_arg;
		int set_in3270_1_arg;
		int set_connected_1_arg;
		termios_rpc set_new_tc_1_arg;
		u_int set_new_tc_c_iflag_1_arg;
		u_int set_new_tc_c_oflag_1_arg;
		u_int set_new_tc_c_cflag_1_arg;
		u_int set_new_tc_c_lflag_1_arg;
		u_char set_new_tc_c_line_1_arg;
		u_int set_new_tc_c_ispeed_1_arg;
		u_int set_new_tc_c_ospeed_1_arg;
		Ring_rpc set_netiring_1_arg;
		char_ptr set_netiring_consume_1_arg;
		char_ptr set_netiring_supply_1_arg;
		char_ptr set_netiring_bottom_1_arg;
		char_ptr set_netiring_top_1_arg;
		char_ptr set_netiring_mark_1_arg;
		int set_netiring_size_1_arg;
		u_long set_netiring_consumetime_1_arg;
		u_long set_netiring_supplytime_1_arg;
		int set_tout_1_arg;
		netibuf_array set_netibuf_1_arg;
		int set_eight_1_arg;
		int set_telnetport_1_arg;
		do_dont_resp_array set_do_dont_resp_1_arg;
		saveline_array set_saveline_1_arg;
		termios_rpc set_old_tc_1_arg;
		u_int set_old_tc_c_iflag_1_arg;
		u_int set_old_tc_c_oflag_1_arg;
		u_int set_old_tc_c_cflag_1_arg;
		u_int set_old_tc_c_lflag_1_arg;
		u_char set_old_tc_c_line_1_arg;
		u_int set_old_tc_c_ispeed_1_arg;
		u_int set_old_tc_c_ospeed_1_arg;
		margv_array set_margv_1_arg;
		line_array set_line_1_arg;
		int set_flushline_1_arg;
		int set_debug_1_arg;
		u_long set_ring_clock_1_arg;
		str_lm_mode_array set_str_lm_mode_1_arg;
		int set_isend_1_arg;
		int set_dontlecho_1_arg;
		int set_kludgelinemode_1_arg;
		int set_net_1_arg;
		char_ptr set_hostname_1_arg;
		int set_margc_1_arg;
		int set_globalmode_1_arg;
		int set_skiprc_1_arg;
		char_ptr set_nettrace_1_arg;
		Ring_rpc set_ttyiring_1_arg;
		char_ptr set_ttyiring_consume_1_arg;
		char_ptr set_ttyiring_supply_1_arg;
		char_ptr set_ttyiring_bottom_1_arg;
		char_ptr set_ttyiring_top_1_arg;
		char_ptr set_ttyiring_mark_1_arg;
		int set_ttyiring_size_1_arg;
		u_long set_ttyiring_consumetime_1_arg;
		u_long set_ttyiring_supplytime_1_arg;
		char_ptr set_prompt_1_arg;
		char_ptr set_user_1_arg;
		char_ptr set_rcname_1_arg;
		int set_local_1_arg;
		Ring_rpc set_ttyoring_1_arg;
		char_ptr set_ttyoring_consume_1_arg;
		char_ptr set_ttyoring_supply_1_arg;
		char_ptr set_ttyoring_bottom_1_arg;
		char_ptr set_ttyoring_top_1_arg;
		char_ptr set_ttyoring_mark_1_arg;
		int set_ttyoring_size_1_arg;
		u_long set_ttyoring_consumetime_1_arg;
		u_long set_ttyoring_supplytime_1_arg;
		ttyobuf_array set_ttyobuf_1_arg;
		subbuffer_array set_subbuffer_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case tn_sense_1_rpc:
		_xdr_argument = (xdrproc_t) xdr_tn_sense_1_rpc_1_argument;
		_xdr_result = (xdrproc_t) xdr_tn_sense_1_ret_;
		local = (char *(*)(char *, struct svc_req *)) _tn_sense_1_rpc_1;
		break;

	case TerminalRead_rpc:
		_xdr_argument = (xdrproc_t) xdr_terminalread_rpc_1_argument;
		_xdr_result = (xdrproc_t) xdr_TerminalRead_ret_;
		local = (char *(*)(char *, struct svc_req *)) _terminalread_rpc_1;
		break;

	case set_escape:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_escape_1;
		break;

	case tninit_rpc:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _tninit_rpc_1;
		break;

	case get_slc_mode:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_slc_mode_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_slc_mode_1;
		break;

	case set_slc_mode:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_slc_mode_1;
		break;

	case get_autologin:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_autologin_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_autologin_1;
		break;

	case set_autologin:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_autologin_1;
		break;

	case get_localflow:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_localflow_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_localflow_1;
		break;

	case set_localflow:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_localflow_1;
		break;

	case get_obits:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_obits_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_obits_1;
		break;

	case set_obits:
		_xdr_argument = (xdrproc_t) xdr_fd_set_rpc;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_obits_1;
		break;

	case get_slc_reply:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_slc_reply_array;
		local = (char *(*)(char *, struct svc_req *)) _get_slc_reply_1;
		break;

	case set_slc_reply:
		_xdr_argument = (xdrproc_t) xdr_slc_reply_array;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_slc_reply_1;
		break;

	case get_netobuf:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_netobuf_array;
		local = (char *(*)(char *, struct svc_req *)) _get_netobuf_1;
		break;

	case set_netobuf:
		_xdr_argument = (xdrproc_t) xdr_netobuf_array;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_netobuf_1;
		break;

	case get_want_status_response:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_want_status_response_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_want_status_response_1;
		break;

	case set_want_status_response:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_want_status_response_1;
		break;

	case get_localchars:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_localchars_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_localchars_1;
		break;

	case set_localchars:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_localchars_1;
		break;

	case get_restartany:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_restartany_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_restartany_1;
		break;

	case set_restartany:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_restartany_1;
		break;

	case get_SYNCHing:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_SYNCHing_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_synching_1;
		break;

	case set_SYNCHing:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_synching_1;
		break;

	case get_termbuf:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_termbuf_array;
		local = (char *(*)(char *, struct svc_req *)) _get_termbuf_1;
		break;

	case set_termbuf:
		_xdr_argument = (xdrproc_t) xdr_termbuf_array;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_termbuf_1;
		break;

	case get_will_wont_resp:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_will_wont_resp_array;
		local = (char *(*)(char *, struct svc_req *)) _get_will_wont_resp_1;
		break;

	case set_will_wont_resp:
		_xdr_argument = (xdrproc_t) xdr_will_wont_resp_array;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_will_wont_resp_1;
		break;

	case get_autoflush:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_autoflush_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_autoflush_1;
		break;

	case set_autoflush:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_autoflush_1;
		break;

	case get_tin:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_tin_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_tin_1;
		break;

	case set_tin:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_tin_1;
		break;

	case get_xbits:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_xbits_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_xbits_1;
		break;

	case set_xbits:
		_xdr_argument = (xdrproc_t) xdr_fd_set_rpc;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_xbits_1;
		break;

	case get_telrcv_state:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_telrcv_state_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_telrcv_state_1;
		break;

	case set_telrcv_state:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_telrcv_state_1;
		break;

	case get_ibits:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_ibits_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_ibits_1;
		break;

	case set_ibits:
		_xdr_argument = (xdrproc_t) xdr_fd_set_rpc;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_ibits_1;
		break;

	case get_linemode:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_linemode_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_linemode_1;
		break;

	case set_linemode:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_linemode_1;
		break;

	case get_bol:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_bol_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_bol_1;
		break;

	case set_bol:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_bol_1;
		break;

	case get_options:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_options_array;
		local = (char *(*)(char *, struct svc_req *)) _get_options_1;
		break;

	case set_options:
		_xdr_argument = (xdrproc_t) xdr_options_array;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_options_1;
		break;

	case get_telopts:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_telopts_array;
		local = (char *(*)(char *, struct svc_req *)) _get_telopts_1;
		break;

	case set_telopts:
		_xdr_argument = (xdrproc_t) xdr_telopts_array;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_telopts_1;
		break;

	case get_str_lm:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_str_lm_array;
		local = (char *(*)(char *, struct svc_req *)) _get_str_lm_1;
		break;

	case set_str_lm:
		_xdr_argument = (xdrproc_t) xdr_str_lm_array;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_str_lm_1;
		break;

	case get_slc_import_val:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_slc_import_val_array;
		local = (char *(*)(char *, struct svc_req *)) _get_slc_import_val_1;
		break;

	case set_slc_import_val:
		_xdr_argument = (xdrproc_t) xdr_slc_import_val_array;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_slc_import_val_1;
		break;

	case get_clocks:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_clocks_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_clocks_1;
		break;

	case set_clocks:
		_xdr_argument = (xdrproc_t) xdr_Clocks_rpc;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_clocks_1;
		break;

	case get_clocks_system:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_clocks_system_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_clocks_system_1;
		break;

	case set_clocks_system:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_clocks_system_1;
		break;

	case get_clocks_echotoggle:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_clocks_echotoggle_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_clocks_echotoggle_1;
		break;

	case set_clocks_echotoggle:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_clocks_echotoggle_1;
		break;

	case get_clocks_modenegotiated:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_clocks_modenegotiated_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_clocks_modenegotiated_1;
		break;

	case set_clocks_modenegotiated:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_clocks_modenegotiated_1;
		break;

	case get_clocks_didnetreceive:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_clocks_didnetreceive_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_clocks_didnetreceive_1;
		break;

	case set_clocks_didnetreceive:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_clocks_didnetreceive_1;
		break;

	case get_clocks_gotDM:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_clocks_gotDM_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_clocks_gotdm_1;
		break;

	case set_clocks_gotDM:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_clocks_gotdm_1;
		break;

	case get_netoring:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_netoring_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_netoring_1;
		break;

	case set_netoring:
		_xdr_argument = (xdrproc_t) xdr_Ring_rpc;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_netoring_1;
		break;

	case get_netoring_consume:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_netoring_consume_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_netoring_consume_1;
		break;

	case set_netoring_consume:
		_xdr_argument = (xdrproc_t) xdr_char_ptr;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_netoring_consume_1;
		break;

	case get_netoring_supply:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_netoring_supply_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_netoring_supply_1;
		break;

	case set_netoring_supply:
		_xdr_argument = (xdrproc_t) xdr_char_ptr;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_netoring_supply_1;
		break;

	case get_netoring_bottom:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_netoring_bottom_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_netoring_bottom_1;
		break;

	case set_netoring_bottom:
		_xdr_argument = (xdrproc_t) xdr_char_ptr;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_netoring_bottom_1;
		break;

	case get_netoring_top:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_netoring_top_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_netoring_top_1;
		break;

	case set_netoring_top:
		_xdr_argument = (xdrproc_t) xdr_char_ptr;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_netoring_top_1;
		break;

	case get_netoring_mark:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_netoring_mark_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_netoring_mark_1;
		break;

	case set_netoring_mark:
		_xdr_argument = (xdrproc_t) xdr_char_ptr;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_netoring_mark_1;
		break;

	case get_netoring_size:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_netoring_size_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_netoring_size_1;
		break;

	case set_netoring_size:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_netoring_size_1;
		break;

	case get_netoring_consumetime:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_netoring_consumetime_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_netoring_consumetime_1;
		break;

	case set_netoring_consumetime:
		_xdr_argument = (xdrproc_t) xdr_u_long;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_netoring_consumetime_1;
		break;

	case get_netoring_supplytime:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_netoring_supplytime_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_netoring_supplytime_1;
		break;

	case set_netoring_supplytime:
		_xdr_argument = (xdrproc_t) xdr_u_long;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_netoring_supplytime_1;
		break;

	case get_crmod:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_crmod_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_crmod_1;
		break;

	case set_crmod:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_crmod_1;
		break;

	case get_donebinarytoggle:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_donebinarytoggle_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_donebinarytoggle_1;
		break;

	case set_donebinarytoggle:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_donebinarytoggle_1;
		break;

	case get_ttyibuf:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_ttyibuf_array;
		local = (char *(*)(char *, struct svc_req *)) _get_ttyibuf_1;
		break;

	case set_ttyibuf:
		_xdr_argument = (xdrproc_t) xdr_ttyibuf_array;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_ttyibuf_1;
		break;

	case get_slc_import_def:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_slc_import_def_array;
		local = (char *(*)(char *, struct svc_req *)) _get_slc_import_def_1;
		break;

	case set_slc_import_def:
		_xdr_argument = (xdrproc_t) xdr_slc_import_def_array;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_slc_import_def_1;
		break;

	case get_resettermname:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_resettermname_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_resettermname_1;
		break;

	case set_resettermname:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_resettermname_1;
		break;

	case get_flushout:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_flushout_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_flushout_1;
		break;

	case set_flushout:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_flushout_1;
		break;

	case get_In3270:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_In3270_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_in3270_1;
		break;

	case set_In3270:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_in3270_1;
		break;

	case get_connected:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_connected_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_connected_1;
		break;

	case set_connected:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_connected_1;
		break;

	case get_new_tc:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_new_tc_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_new_tc_1;
		break;

	case set_new_tc:
		_xdr_argument = (xdrproc_t) xdr_termios_rpc;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_new_tc_1;
		break;

	case get_new_tc_c_iflag:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_new_tc_c_iflag_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_new_tc_c_iflag_1;
		break;

	case set_new_tc_c_iflag:
		_xdr_argument = (xdrproc_t) xdr_u_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_new_tc_c_iflag_1;
		break;

	case get_new_tc_c_oflag:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_new_tc_c_oflag_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_new_tc_c_oflag_1;
		break;

	case set_new_tc_c_oflag:
		_xdr_argument = (xdrproc_t) xdr_u_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_new_tc_c_oflag_1;
		break;

	case get_new_tc_c_cflag:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_new_tc_c_cflag_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_new_tc_c_cflag_1;
		break;

	case set_new_tc_c_cflag:
		_xdr_argument = (xdrproc_t) xdr_u_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_new_tc_c_cflag_1;
		break;

	case get_new_tc_c_lflag:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_new_tc_c_lflag_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_new_tc_c_lflag_1;
		break;

	case set_new_tc_c_lflag:
		_xdr_argument = (xdrproc_t) xdr_u_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_new_tc_c_lflag_1;
		break;

	case get_new_tc_c_line:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_new_tc_c_line_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_new_tc_c_line_1;
		break;

	case set_new_tc_c_line:
		_xdr_argument = (xdrproc_t) xdr_u_char;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_new_tc_c_line_1;
		break;

	case get_new_tc_c_ispeed:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_new_tc_c_ispeed_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_new_tc_c_ispeed_1;
		break;

	case set_new_tc_c_ispeed:
		_xdr_argument = (xdrproc_t) xdr_u_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_new_tc_c_ispeed_1;
		break;

	case get_new_tc_c_ospeed:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_new_tc_c_ospeed_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_new_tc_c_ospeed_1;
		break;

	case set_new_tc_c_ospeed:
		_xdr_argument = (xdrproc_t) xdr_u_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_new_tc_c_ospeed_1;
		break;

	case get_netiring:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_netiring_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_netiring_1;
		break;

	case set_netiring:
		_xdr_argument = (xdrproc_t) xdr_Ring_rpc;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_netiring_1;
		break;

	case get_netiring_consume:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_netiring_consume_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_netiring_consume_1;
		break;

	case set_netiring_consume:
		_xdr_argument = (xdrproc_t) xdr_char_ptr;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_netiring_consume_1;
		break;

	case get_netiring_supply:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_netiring_supply_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_netiring_supply_1;
		break;

	case set_netiring_supply:
		_xdr_argument = (xdrproc_t) xdr_char_ptr;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_netiring_supply_1;
		break;

	case get_netiring_bottom:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_netiring_bottom_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_netiring_bottom_1;
		break;

	case set_netiring_bottom:
		_xdr_argument = (xdrproc_t) xdr_char_ptr;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_netiring_bottom_1;
		break;

	case get_netiring_top:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_netiring_top_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_netiring_top_1;
		break;

	case set_netiring_top:
		_xdr_argument = (xdrproc_t) xdr_char_ptr;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_netiring_top_1;
		break;

	case get_netiring_mark:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_netiring_mark_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_netiring_mark_1;
		break;

	case set_netiring_mark:
		_xdr_argument = (xdrproc_t) xdr_char_ptr;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_netiring_mark_1;
		break;

	case get_netiring_size:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_netiring_size_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_netiring_size_1;
		break;

	case set_netiring_size:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_netiring_size_1;
		break;

	case get_netiring_consumetime:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_netiring_consumetime_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_netiring_consumetime_1;
		break;

	case set_netiring_consumetime:
		_xdr_argument = (xdrproc_t) xdr_u_long;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_netiring_consumetime_1;
		break;

	case get_netiring_supplytime:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_netiring_supplytime_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_netiring_supplytime_1;
		break;

	case set_netiring_supplytime:
		_xdr_argument = (xdrproc_t) xdr_u_long;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_netiring_supplytime_1;
		break;

	case get_tout:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_tout_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_tout_1;
		break;

	case set_tout:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_tout_1;
		break;

	case get_netibuf:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_netibuf_array;
		local = (char *(*)(char *, struct svc_req *)) _get_netibuf_1;
		break;

	case set_netibuf:
		_xdr_argument = (xdrproc_t) xdr_netibuf_array;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_netibuf_1;
		break;

	case get_eight:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_eight_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_eight_1;
		break;

	case set_eight:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_eight_1;
		break;

	case get_telnetport:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_telnetport_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_telnetport_1;
		break;

	case set_telnetport:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_telnetport_1;
		break;

	case get_do_dont_resp:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_do_dont_resp_array;
		local = (char *(*)(char *, struct svc_req *)) _get_do_dont_resp_1;
		break;

	case set_do_dont_resp:
		_xdr_argument = (xdrproc_t) xdr_do_dont_resp_array;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_do_dont_resp_1;
		break;

	case get_saveline:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_saveline_array;
		local = (char *(*)(char *, struct svc_req *)) _get_saveline_1;
		break;

	case set_saveline:
		_xdr_argument = (xdrproc_t) xdr_saveline_array;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_saveline_1;
		break;

	case get_old_tc:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_old_tc_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_old_tc_1;
		break;

	case set_old_tc:
		_xdr_argument = (xdrproc_t) xdr_termios_rpc;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_old_tc_1;
		break;

	case get_old_tc_c_iflag:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_old_tc_c_iflag_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_old_tc_c_iflag_1;
		break;

	case set_old_tc_c_iflag:
		_xdr_argument = (xdrproc_t) xdr_u_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_old_tc_c_iflag_1;
		break;

	case get_old_tc_c_oflag:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_old_tc_c_oflag_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_old_tc_c_oflag_1;
		break;

	case set_old_tc_c_oflag:
		_xdr_argument = (xdrproc_t) xdr_u_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_old_tc_c_oflag_1;
		break;

	case get_old_tc_c_cflag:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_old_tc_c_cflag_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_old_tc_c_cflag_1;
		break;

	case set_old_tc_c_cflag:
		_xdr_argument = (xdrproc_t) xdr_u_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_old_tc_c_cflag_1;
		break;

	case get_old_tc_c_lflag:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_old_tc_c_lflag_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_old_tc_c_lflag_1;
		break;

	case set_old_tc_c_lflag:
		_xdr_argument = (xdrproc_t) xdr_u_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_old_tc_c_lflag_1;
		break;

	case get_old_tc_c_line:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_old_tc_c_line_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_old_tc_c_line_1;
		break;

	case set_old_tc_c_line:
		_xdr_argument = (xdrproc_t) xdr_u_char;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_old_tc_c_line_1;
		break;

	case get_old_tc_c_ispeed:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_old_tc_c_ispeed_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_old_tc_c_ispeed_1;
		break;

	case set_old_tc_c_ispeed:
		_xdr_argument = (xdrproc_t) xdr_u_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_old_tc_c_ispeed_1;
		break;

	case get_old_tc_c_ospeed:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_old_tc_c_ospeed_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_old_tc_c_ospeed_1;
		break;

	case set_old_tc_c_ospeed:
		_xdr_argument = (xdrproc_t) xdr_u_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_old_tc_c_ospeed_1;
		break;

	case get_margv:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_margv_array;
		local = (char *(*)(char *, struct svc_req *)) _get_margv_1;
		break;

	case set_margv:
		_xdr_argument = (xdrproc_t) xdr_margv_array;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_margv_1;
		break;

	case get_line:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_line_array;
		local = (char *(*)(char *, struct svc_req *)) _get_line_1;
		break;

	case set_line:
		_xdr_argument = (xdrproc_t) xdr_line_array;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_line_1;
		break;

	case get_flushline:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_flushline_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_flushline_1;
		break;

	case set_flushline:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_flushline_1;
		break;

	case get_debug:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_debug_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_debug_1;
		break;

	case set_debug:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_debug_1;
		break;

	case get_ring_clock:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_ring_clock_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_ring_clock_1;
		break;

	case set_ring_clock:
		_xdr_argument = (xdrproc_t) xdr_u_long;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_ring_clock_1;
		break;

	case get_str_lm_mode:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_str_lm_mode_array;
		local = (char *(*)(char *, struct svc_req *)) _get_str_lm_mode_1;
		break;

	case set_str_lm_mode:
		_xdr_argument = (xdrproc_t) xdr_str_lm_mode_array;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_str_lm_mode_1;
		break;

	case get_ISend:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_ISend_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_isend_1;
		break;

	case set_ISend:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_isend_1;
		break;

	case get_dontlecho:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_dontlecho_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_dontlecho_1;
		break;

	case set_dontlecho:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_dontlecho_1;
		break;

	case get_kludgelinemode:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_kludgelinemode_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_kludgelinemode_1;
		break;

	case set_kludgelinemode:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_kludgelinemode_1;
		break;

	case get_net:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_net_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_net_1;
		break;

	case set_net:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_net_1;
		break;

	case get_hostname:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_char_ptr;
		local = (char *(*)(char *, struct svc_req *)) _get_hostname_1;
		break;

	case set_hostname:
		_xdr_argument = (xdrproc_t) xdr_char_ptr;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_hostname_1;
		break;

	case get_margc:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_margc_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_margc_1;
		break;

	case set_margc:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_margc_1;
		break;

	case get_globalmode:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_globalmode_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_globalmode_1;
		break;

	case set_globalmode:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_globalmode_1;
		break;

	case get_skiprc:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_skiprc_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_skiprc_1;
		break;

	case set_skiprc:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_skiprc_1;
		break;

	case get_NetTrace:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_char_ptr;
		local = (char *(*)(char *, struct svc_req *)) _get_nettrace_1;
		break;

	case set_NetTrace:
		_xdr_argument = (xdrproc_t) xdr_char_ptr;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_nettrace_1;
		break;

	case get_ttyiring:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_ttyiring_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_ttyiring_1;
		break;

	case set_ttyiring:
		_xdr_argument = (xdrproc_t) xdr_Ring_rpc;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_ttyiring_1;
		break;

	case get_ttyiring_consume:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_ttyiring_consume_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_ttyiring_consume_1;
		break;

	case set_ttyiring_consume:
		_xdr_argument = (xdrproc_t) xdr_char_ptr;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_ttyiring_consume_1;
		break;

	case get_ttyiring_supply:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_ttyiring_supply_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_ttyiring_supply_1;
		break;

	case set_ttyiring_supply:
		_xdr_argument = (xdrproc_t) xdr_char_ptr;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_ttyiring_supply_1;
		break;

	case get_ttyiring_bottom:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_ttyiring_bottom_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_ttyiring_bottom_1;
		break;

	case set_ttyiring_bottom:
		_xdr_argument = (xdrproc_t) xdr_char_ptr;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_ttyiring_bottom_1;
		break;

	case get_ttyiring_top:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_ttyiring_top_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_ttyiring_top_1;
		break;

	case set_ttyiring_top:
		_xdr_argument = (xdrproc_t) xdr_char_ptr;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_ttyiring_top_1;
		break;

	case get_ttyiring_mark:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_ttyiring_mark_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_ttyiring_mark_1;
		break;

	case set_ttyiring_mark:
		_xdr_argument = (xdrproc_t) xdr_char_ptr;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_ttyiring_mark_1;
		break;

	case get_ttyiring_size:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_ttyiring_size_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_ttyiring_size_1;
		break;

	case set_ttyiring_size:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_ttyiring_size_1;
		break;

	case get_ttyiring_consumetime:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_ttyiring_consumetime_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_ttyiring_consumetime_1;
		break;

	case set_ttyiring_consumetime:
		_xdr_argument = (xdrproc_t) xdr_u_long;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_ttyiring_consumetime_1;
		break;

	case get_ttyiring_supplytime:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_ttyiring_supplytime_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_ttyiring_supplytime_1;
		break;

	case set_ttyiring_supplytime:
		_xdr_argument = (xdrproc_t) xdr_u_long;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_ttyiring_supplytime_1;
		break;

	case get_prompt:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_char_ptr;
		local = (char *(*)(char *, struct svc_req *)) _get_prompt_1;
		break;

	case set_prompt:
		_xdr_argument = (xdrproc_t) xdr_char_ptr;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_prompt_1;
		break;

	case get_user:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_char_ptr;
		local = (char *(*)(char *, struct svc_req *)) _get_user_1;
		break;

	case set_user:
		_xdr_argument = (xdrproc_t) xdr_char_ptr;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_user_1;
		break;

	case get_rcname:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_char_ptr;
		local = (char *(*)(char *, struct svc_req *)) _get_rcname_1;
		break;

	case set_rcname:
		_xdr_argument = (xdrproc_t) xdr_char_ptr;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_rcname_1;
		break;

	case get_local:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_local_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_local_1;
		break;

	case set_local:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_local_1;
		break;

	case get_ttyoring:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_ttyoring_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_ttyoring_1;
		break;

	case set_ttyoring:
		_xdr_argument = (xdrproc_t) xdr_Ring_rpc;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_ttyoring_1;
		break;

	case get_ttyoring_consume:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_ttyoring_consume_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_ttyoring_consume_1;
		break;

	case set_ttyoring_consume:
		_xdr_argument = (xdrproc_t) xdr_char_ptr;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_ttyoring_consume_1;
		break;

	case get_ttyoring_supply:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_ttyoring_supply_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_ttyoring_supply_1;
		break;

	case set_ttyoring_supply:
		_xdr_argument = (xdrproc_t) xdr_char_ptr;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_ttyoring_supply_1;
		break;

	case get_ttyoring_bottom:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_ttyoring_bottom_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_ttyoring_bottom_1;
		break;

	case set_ttyoring_bottom:
		_xdr_argument = (xdrproc_t) xdr_char_ptr;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_ttyoring_bottom_1;
		break;

	case get_ttyoring_top:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_ttyoring_top_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_ttyoring_top_1;
		break;

	case set_ttyoring_top:
		_xdr_argument = (xdrproc_t) xdr_char_ptr;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_ttyoring_top_1;
		break;

	case get_ttyoring_mark:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_ttyoring_mark_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_ttyoring_mark_1;
		break;

	case set_ttyoring_mark:
		_xdr_argument = (xdrproc_t) xdr_char_ptr;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_ttyoring_mark_1;
		break;

	case get_ttyoring_size:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_ttyoring_size_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_ttyoring_size_1;
		break;

	case set_ttyoring_size:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_ttyoring_size_1;
		break;

	case get_ttyoring_consumetime:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_ttyoring_consumetime_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_ttyoring_consumetime_1;
		break;

	case set_ttyoring_consumetime:
		_xdr_argument = (xdrproc_t) xdr_u_long;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_ttyoring_consumetime_1;
		break;

	case get_ttyoring_supplytime:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_ttyoring_supplytime_ret_t;
		local = (char *(*)(char *, struct svc_req *)) _get_ttyoring_supplytime_1;
		break;

	case set_ttyoring_supplytime:
		_xdr_argument = (xdrproc_t) xdr_u_long;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_ttyoring_supplytime_1;
		break;

	case get_ttyobuf:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_ttyobuf_array;
		local = (char *(*)(char *, struct svc_req *)) _get_ttyobuf_1;
		break;

	case set_ttyobuf:
		_xdr_argument = (xdrproc_t) xdr_ttyobuf_array;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_ttyobuf_1;
		break;

	case get_subbuffer:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_subbuffer_array;
		local = (char *(*)(char *, struct svc_req *)) _get_subbuffer_1;
		break;

	case set_subbuffer:
		_xdr_argument = (xdrproc_t) xdr_subbuffer_array;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _set_subbuffer_1;
		break;

	case gsetter_want_status_response_prefix:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _gsetter_want_status_response_prefix_1;
		break;

	case gsetter_margc_postfix:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _gsetter_margc_postfix_1;
		break;

	case gsetter_prompt_prefix:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _gsetter_prompt_prefix_1;
		break;

	case gsetter_subpointer_postfix:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_char_ptr;
		local = (char *(*)(char *, struct svc_req *)) _gsetter_subpointer_postfix_1;
		break;

	case gsetter_slc_replyp_postfix:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_char_ptr;
		local = (char *(*)(char *, struct svc_req *)) _gsetter_slc_replyp_postfix_1;
		break;

	case gsetter_opt_replyp_postfix:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_char_ptr;
		local = (char *(*)(char *, struct svc_req *)) _gsetter_opt_replyp_postfix_1;
		break;

	case gsetter_ring_clock_prefix:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_u_long;
		local = (char *(*)(char *, struct svc_req *)) _gsetter_ring_clock_prefix_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (RPCTELNET, RPCTELNETTVERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, RPCTELNET, RPCTELNETTVERS, rpctelnet_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (RPCTELNET, RPCTELNETTVERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, RPCTELNET, RPCTELNETTVERS, rpctelnet_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (RPCTELNET, RPCTELNETTVERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
