/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */
#include "config.h"
#include "telnet_idl.h"

bool_t
xdr_int_ptr (XDR *xdrs, int_ptr *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->int_ptr_val, (u_int *) &objp->int_ptr_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_sockaddr_rpc (XDR *xdrs, sockaddr_rpc *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->sa_family))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->sa_data, 14,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_sockaddr_rpc_ptr (XDR *xdrs, sockaddr_rpc_ptr *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->sockaddr_rpc_ptr_val, (u_int *) &objp->sockaddr_rpc_ptr_len, ~0,
		sizeof (sockaddr_rpc), (xdrproc_t) xdr_sockaddr_rpc))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_char_ptr (XDR *xdrs, char_ptr *objp)
{
	register int32_t *buf;

	 if (!xdr_bytes (xdrs, (char **)&objp->charptr.charptr_val, (u_int *) &objp->charptr.charptr_len, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_addrinfo_rpc (XDR *xdrs, addrinfo_rpc *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->ai_flags))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->ai_family))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->ai_socktype))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->ai_protocol))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->ai_addrlen))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->ai_flags);
		IXDR_PUT_LONG(buf, objp->ai_family);
		IXDR_PUT_LONG(buf, objp->ai_socktype);
		IXDR_PUT_LONG(buf, objp->ai_protocol);
		IXDR_PUT_LONG(buf, objp->ai_addrlen);
		}
		 if (!xdr_sockaddr_rpc (xdrs, &objp->ai_addr))
			 return FALSE;
		 if (!xdr_char_ptr (xdrs, &objp->ai_canonname))
			 return FALSE;
		 if (!xdr_pointer (xdrs, (char **)&objp->ai_next, sizeof (addrinfo_rpc), (xdrproc_t) xdr_addrinfo_rpc))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->ai_flags))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->ai_family))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->ai_socktype))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->ai_protocol))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->ai_addrlen))
				 return FALSE;

		} else {
		objp->ai_flags = IXDR_GET_LONG(buf);
		objp->ai_family = IXDR_GET_LONG(buf);
		objp->ai_socktype = IXDR_GET_LONG(buf);
		objp->ai_protocol = IXDR_GET_LONG(buf);
		objp->ai_addrlen = IXDR_GET_LONG(buf);
		}
		 if (!xdr_sockaddr_rpc (xdrs, &objp->ai_addr))
			 return FALSE;
		 if (!xdr_char_ptr (xdrs, &objp->ai_canonname))
			 return FALSE;
		 if (!xdr_pointer (xdrs, (char **)&objp->ai_next, sizeof (addrinfo_rpc), (xdrproc_t) xdr_addrinfo_rpc))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->ai_flags))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ai_family))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ai_socktype))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ai_protocol))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ai_addrlen))
		 return FALSE;
	 if (!xdr_sockaddr_rpc (xdrs, &objp->ai_addr))
		 return FALSE;
	 if (!xdr_char_ptr (xdrs, &objp->ai_canonname))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->ai_next, sizeof (addrinfo_rpc), (xdrproc_t) xdr_addrinfo_rpc))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_addrinfo_rpc_ptr (XDR *xdrs, addrinfo_rpc_ptr *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->addrinfo_rpc_ptr_val, (u_int *) &objp->addrinfo_rpc_ptr_len, ~0,
		sizeof (addrinfo_rpc), (xdrproc_t) xdr_addrinfo_rpc))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_tn_sense_1_ret_ (XDR *xdrs, tn_sense_1_ret_ *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->ret0))
		 return FALSE;
	 if (!xdr_int_ptr (xdrs, &objp->tn_sense_1_ret))
		 return FALSE;
	 if (!xdr_addrinfo_rpc_ptr (xdrs, &objp->result))
		 return FALSE;
	 if (!xdr_addrinfo_rpc_ptr (xdrs, &objp->aip))
		 return FALSE;
	 if (!xdr_int_ptr (xdrs, &objp->err))
		 return FALSE;
	 if (!xdr_char_ptr (xdrs, &objp->hostp))
		 return FALSE;
	 if (!xdr_char_ptr (xdrs, &objp->portp))
		 return FALSE;
	 if (!xdr_char_ptr (xdrs, &objp->user))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TerminalRead_ret_ (XDR *xdrs, TerminalRead_ret_ *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->ret0))
		 return FALSE;
	 if (!xdr_char_ptr (xdrs, &objp->buf))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_slc_mode_ret_t (XDR *xdrs, slc_mode_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_autologin_ret_t (XDR *xdrs, autologin_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_localflow_ret_t (XDR *xdrs, localflow_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_fd_set_rpc (XDR *xdrs, fd_set_rpc *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, ( 16 ) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->__fds_bits, 16,
				sizeof (long), (xdrproc_t) xdr_long))
				 return FALSE;
		} else {
			{
				register long *genp;

				for (i = 0, genp = objp->__fds_bits;
					i < 16; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, ( 16 ) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->__fds_bits, 16,
				sizeof (long), (xdrproc_t) xdr_long))
				 return FALSE;
		} else {
			{
				register long *genp;

				for (i = 0, genp = objp->__fds_bits;
					i < 16; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
		}
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->__fds_bits, 16,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_obits_ret_t (XDR *xdrs, obits_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_fd_set_rpc (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_slc_reply_array (XDR *xdrs, slc_reply_array *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->slc_reply, 128,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_netobuf_array (XDR *xdrs, netobuf_array *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->netobuf, 2048,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_want_status_response_ret_t (XDR *xdrs, want_status_response_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_localchars_ret_t (XDR *xdrs, localchars_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_restartany_ret_t (XDR *xdrs, restartany_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_SYNCHing_ret_t (XDR *xdrs, SYNCHing_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_termbuf_array (XDR *xdrs, termbuf_array *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->termbuf, 2048,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_will_wont_resp_array (XDR *xdrs, will_wont_resp_array *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->will_wont_resp, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_autoflush_ret_t (XDR *xdrs, autoflush_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_tin_ret_t (XDR *xdrs, tin_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_xbits_ret_t (XDR *xdrs, xbits_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_fd_set_rpc (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_telrcv_state_ret_t (XDR *xdrs, telrcv_state_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ibits_ret_t (XDR *xdrs, ibits_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_fd_set_rpc (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_slclist_rpc (XDR *xdrs, slclist_rpc *objp)
{
	register int32_t *buf;

	 if (!xdr_char_ptr (xdrs, &objp->name))
		 return FALSE;
	 if (!xdr_char_ptr (xdrs, &objp->help))
		 return FALSE;
	 if (!xdr_char_ptr (xdrs, &objp->handler))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_linemode_ret_t (XDR *xdrs, linemode_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_bol_ret_t (XDR *xdrs, bol_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_options_array (XDR *xdrs, options_array *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->options, 1,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_telopts_array (XDR *xdrs, telopts_array *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->telopts, 41,
		sizeof (char_ptr), (xdrproc_t) xdr_char_ptr))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_str_lm_array (XDR *xdrs, str_lm_array *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->str_lm, 1,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_slc_import_val_array (XDR *xdrs, slc_import_val_array *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->slc_import_val, 1,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Clocks_rpc (XDR *xdrs, Clocks_rpc *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->system))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->echotoggle))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->modenegotiated))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->didnetreceive))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->gotDM))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->system);
			IXDR_PUT_LONG(buf, objp->echotoggle);
			IXDR_PUT_LONG(buf, objp->modenegotiated);
			IXDR_PUT_LONG(buf, objp->didnetreceive);
			IXDR_PUT_LONG(buf, objp->gotDM);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->system))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->echotoggle))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->modenegotiated))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->didnetreceive))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->gotDM))
				 return FALSE;
		} else {
			objp->system = IXDR_GET_LONG(buf);
			objp->echotoggle = IXDR_GET_LONG(buf);
			objp->modenegotiated = IXDR_GET_LONG(buf);
			objp->didnetreceive = IXDR_GET_LONG(buf);
			objp->gotDM = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->system))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->echotoggle))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->modenegotiated))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->didnetreceive))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->gotDM))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_clocks_ret_t (XDR *xdrs, clocks_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_Clocks_rpc (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_clocks_system_ret_t (XDR *xdrs, clocks_system_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_clocks_echotoggle_ret_t (XDR *xdrs, clocks_echotoggle_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_clocks_modenegotiated_ret_t (XDR *xdrs, clocks_modenegotiated_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_clocks_didnetreceive_ret_t (XDR *xdrs, clocks_didnetreceive_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_clocks_gotDM_ret_t (XDR *xdrs, clocks_gotDM_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Ring_rpc (XDR *xdrs, Ring_rpc *objp)
{
	register int32_t *buf;

	 if (!xdr_char_ptr (xdrs, &objp->consume))
		 return FALSE;
	 if (!xdr_char_ptr (xdrs, &objp->supply))
		 return FALSE;
	 if (!xdr_char_ptr (xdrs, &objp->bottom))
		 return FALSE;
	 if (!xdr_char_ptr (xdrs, &objp->top))
		 return FALSE;
	 if (!xdr_char_ptr (xdrs, &objp->mark))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->consumetime))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->supplytime))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_netoring_ret_t (XDR *xdrs, netoring_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_Ring_rpc (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_netoring_consume_ret_t (XDR *xdrs, netoring_consume_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_char_ptr (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_netoring_supply_ret_t (XDR *xdrs, netoring_supply_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_char_ptr (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_netoring_bottom_ret_t (XDR *xdrs, netoring_bottom_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_char_ptr (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_netoring_top_ret_t (XDR *xdrs, netoring_top_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_char_ptr (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_netoring_mark_ret_t (XDR *xdrs, netoring_mark_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_char_ptr (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_netoring_size_ret_t (XDR *xdrs, netoring_size_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_netoring_consumetime_ret_t (XDR *xdrs, netoring_consumetime_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_u_long (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_netoring_supplytime_ret_t (XDR *xdrs, netoring_supplytime_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_u_long (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_crmod_ret_t (XDR *xdrs, crmod_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_donebinarytoggle_ret_t (XDR *xdrs, donebinarytoggle_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ttyibuf_array (XDR *xdrs, ttyibuf_array *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->ttyibuf, 1024,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_slc_import_def_array (XDR *xdrs, slc_import_def_array *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->slc_import_def, 1,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_resettermname_ret_t (XDR *xdrs, resettermname_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_flushout_ret_t (XDR *xdrs, flushout_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_In3270_ret_t (XDR *xdrs, In3270_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_connected_ret_t (XDR *xdrs, connected_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_termios_rpc (XDR *xdrs, termios_rpc *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->c_iflag))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->c_oflag))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->c_cflag))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->c_lflag))
				 return FALSE;

		} else {
		IXDR_PUT_U_LONG(buf, objp->c_iflag);
		IXDR_PUT_U_LONG(buf, objp->c_oflag);
		IXDR_PUT_U_LONG(buf, objp->c_cflag);
		IXDR_PUT_U_LONG(buf, objp->c_lflag);
		}
		 if (!xdr_u_char (xdrs, &objp->c_line))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->c_cc, 32,
			sizeof (u_char), (xdrproc_t) xdr_u_char))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->c_ispeed))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->c_ospeed))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->c_iflag))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->c_oflag))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->c_cflag))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->c_lflag))
				 return FALSE;

		} else {
		objp->c_iflag = IXDR_GET_U_LONG(buf);
		objp->c_oflag = IXDR_GET_U_LONG(buf);
		objp->c_cflag = IXDR_GET_U_LONG(buf);
		objp->c_lflag = IXDR_GET_U_LONG(buf);
		}
		 if (!xdr_u_char (xdrs, &objp->c_line))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->c_cc, 32,
			sizeof (u_char), (xdrproc_t) xdr_u_char))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->c_ispeed))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->c_ospeed))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_u_int (xdrs, &objp->c_iflag))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->c_oflag))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->c_cflag))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->c_lflag))
		 return FALSE;
	 if (!xdr_u_char (xdrs, &objp->c_line))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->c_cc, 32,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->c_ispeed))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->c_ospeed))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_new_tc_ret_t (XDR *xdrs, new_tc_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_termios_rpc (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_new_tc_c_iflag_ret_t (XDR *xdrs, new_tc_c_iflag_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_new_tc_c_oflag_ret_t (XDR *xdrs, new_tc_c_oflag_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_new_tc_c_cflag_ret_t (XDR *xdrs, new_tc_c_cflag_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_new_tc_c_lflag_ret_t (XDR *xdrs, new_tc_c_lflag_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_new_tc_c_line_ret_t (XDR *xdrs, new_tc_c_line_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_u_char (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_new_tc_c_ispeed_ret_t (XDR *xdrs, new_tc_c_ispeed_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_new_tc_c_ospeed_ret_t (XDR *xdrs, new_tc_c_ospeed_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_netiring_ret_t (XDR *xdrs, netiring_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_Ring_rpc (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_netiring_consume_ret_t (XDR *xdrs, netiring_consume_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_char_ptr (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_netiring_supply_ret_t (XDR *xdrs, netiring_supply_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_char_ptr (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_netiring_bottom_ret_t (XDR *xdrs, netiring_bottom_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_char_ptr (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_netiring_top_ret_t (XDR *xdrs, netiring_top_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_char_ptr (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_netiring_mark_ret_t (XDR *xdrs, netiring_mark_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_char_ptr (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_netiring_size_ret_t (XDR *xdrs, netiring_size_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_netiring_consumetime_ret_t (XDR *xdrs, netiring_consumetime_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_u_long (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_netiring_supplytime_ret_t (XDR *xdrs, netiring_supplytime_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_u_long (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_tout_ret_t (XDR *xdrs, tout_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_netibuf_array (XDR *xdrs, netibuf_array *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->netibuf, 1024,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_eight_ret_t (XDR *xdrs, eight_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_telnetport_ret_t (XDR *xdrs, telnetport_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_do_dont_resp_array (XDR *xdrs, do_dont_resp_array *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->do_dont_resp, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_saveline_array (XDR *xdrs, saveline_array *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->saveline, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_old_tc_ret_t (XDR *xdrs, old_tc_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_termios_rpc (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_old_tc_c_iflag_ret_t (XDR *xdrs, old_tc_c_iflag_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_old_tc_c_oflag_ret_t (XDR *xdrs, old_tc_c_oflag_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_old_tc_c_cflag_ret_t (XDR *xdrs, old_tc_c_cflag_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_old_tc_c_lflag_ret_t (XDR *xdrs, old_tc_c_lflag_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_old_tc_c_line_ret_t (XDR *xdrs, old_tc_c_line_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_u_char (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_old_tc_c_ispeed_ret_t (XDR *xdrs, old_tc_c_ispeed_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_old_tc_c_ospeed_ret_t (XDR *xdrs, old_tc_c_ospeed_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Command_rpc (XDR *xdrs, Command_rpc *objp)
{
	register int32_t *buf;

	 if (!xdr_char_ptr (xdrs, &objp->name))
		 return FALSE;
	 if (!xdr_char_ptr (xdrs, &objp->help))
		 return FALSE;
	 if (!xdr_char_ptr (xdrs, &objp->handler))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->needconnect))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_margv_array (XDR *xdrs, margv_array *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->margv, 20,
		sizeof (char_ptr), (xdrproc_t) xdr_char_ptr))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_line_array (XDR *xdrs, line_array *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->line, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_flushline_ret_t (XDR *xdrs, flushline_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_debug_ret_t (XDR *xdrs, debug_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ring_clock_ret_t (XDR *xdrs, ring_clock_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_u_long (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_str_lm_mode_array (XDR *xdrs, str_lm_mode_array *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->str_lm_mode, 1,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ISend_ret_t (XDR *xdrs, ISend_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_dontlecho_ret_t (XDR *xdrs, dontlecho_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_kludgelinemode_ret_t (XDR *xdrs, kludgelinemode_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_net_ret_t (XDR *xdrs, net_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_margc_ret_t (XDR *xdrs, margc_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_globalmode_ret_t (XDR *xdrs, globalmode_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_skiprc_ret_t (XDR *xdrs, skiprc_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ttyiring_ret_t (XDR *xdrs, ttyiring_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_Ring_rpc (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ttyiring_consume_ret_t (XDR *xdrs, ttyiring_consume_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_char_ptr (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ttyiring_supply_ret_t (XDR *xdrs, ttyiring_supply_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_char_ptr (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ttyiring_bottom_ret_t (XDR *xdrs, ttyiring_bottom_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_char_ptr (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ttyiring_top_ret_t (XDR *xdrs, ttyiring_top_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_char_ptr (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ttyiring_mark_ret_t (XDR *xdrs, ttyiring_mark_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_char_ptr (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ttyiring_size_ret_t (XDR *xdrs, ttyiring_size_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ttyiring_consumetime_ret_t (XDR *xdrs, ttyiring_consumetime_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_u_long (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ttyiring_supplytime_ret_t (XDR *xdrs, ttyiring_supplytime_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_u_long (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_local_ret_t (XDR *xdrs, local_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ttyoring_ret_t (XDR *xdrs, ttyoring_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_Ring_rpc (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ttyoring_consume_ret_t (XDR *xdrs, ttyoring_consume_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_char_ptr (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ttyoring_supply_ret_t (XDR *xdrs, ttyoring_supply_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_char_ptr (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ttyoring_bottom_ret_t (XDR *xdrs, ttyoring_bottom_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_char_ptr (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ttyoring_top_ret_t (XDR *xdrs, ttyoring_top_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_char_ptr (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ttyoring_mark_ret_t (XDR *xdrs, ttyoring_mark_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_char_ptr (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ttyoring_size_ret_t (XDR *xdrs, ttyoring_size_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ttyoring_consumetime_ret_t (XDR *xdrs, ttyoring_consumetime_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_u_long (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ttyoring_supplytime_ret_t (XDR *xdrs, ttyoring_supplytime_ret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_u_long (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ttyobuf_array (XDR *xdrs, ttyobuf_array *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->ttyobuf, 2048,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_subbuffer_array (XDR *xdrs, subbuffer_array *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->subbuffer, 256,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_tn_sense_1_rpc_1_argument (XDR *xdrs, tn_sense_1_rpc_1_argument *objp)
{
	 if (!xdr_int_ptr (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_addrinfo_rpc_ptr (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_addrinfo_rpc_ptr (xdrs, &objp->arg3))
		 return FALSE;
	 if (!xdr_addrinfo_rpc (xdrs, &objp->arg4))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg5))
		 return FALSE;
	 if (!xdr_int_ptr (xdrs, &objp->arg6))
		 return FALSE;
	 if (!xdr_char_ptr (xdrs, &objp->arg7))
		 return FALSE;
	 if (!xdr_char_ptr (xdrs, &objp->arg8))
		 return FALSE;
	 if (!xdr_char_ptr (xdrs, &objp->arg9))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_terminalread_rpc_1_argument (XDR *xdrs, terminalread_rpc_1_argument *objp)
{
	 if (!xdr_char_ptr (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}
