/* version.c */
/* Autogenerated by Makefile - DO NOT EDIT */

#include "version.h"
const char *version_string = "1.18";
const char *compilation_string = "gcc -DHAVE_CONFIG_H -DSYSTEM_WGETRC=\"/usr/local/etc/wgetrc\" -DLOCALEDIR=\"/usr/local/share/locale\" -I. -I../lib -I../lib -g -O0 -m32 -I/flowcheck/include";
const char *link_string = "gcc -g -O0 -m32 -I/flowcheck/include -lpcre -lgnutls -lz -lpsl ftp-opie.o gnutls.o ../lib/libgnu.a";
